name: Continuous Integration GitActions
on:
  push:
    branches: 
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./javaboot/fivespring
      run: mvn clean package -DskipTests
      
    - name: Build Docker Container Application
      working-directory: ./javaboot
      run: docker compose build
      
    - name: Docker Push Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/fivespring:latest ${{ secrets.DOCKER_USERNAME }}/fivespring:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/fivespring:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/fivespring:latest
        
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
